"""
AegisX Windows Agent
=====================
Runs locally on an authorized Windows machine. Collects REAL process-creation
telemetry and network-connection metadata using psutil, and sends it to your
deployed AegisX backend (Supabase Edge Functions).

This is not a simulation library — psutil reads live OS process/network
tables. There is no fake/sample data generated by this script; if nothing is
running on the machine that matches a rule, nothing gets flagged.

SETUP
-----
1. pip install -r requirements.txt
2. Copy config.example.json to config.json and fill in:
     - backend_url   -> e.g. https://<your-project>.supabase.co/functions/v1
     - enroll_key    -> from your AegisX Settings page (per-organization key)
3. Run:  python agent.py
   First run performs enrollment and saves a device_token into config.json.
   Subsequent runs reuse the saved token.

WHAT IT ACTUALLY DOES
----------------------
- Polls running processes every POLL_INTERVAL_SECONDS via psutil.
- Detects NEW process creations since the last poll (real, not simulated).
- Detects parent -> child relationships (e.g. WINWORD.EXE -> POWERSHELL.EXE).
- Reads the real command line of each new process (requires admin on Windows
  to see command lines of processes not owned by the current user).
- Reads real outbound network connections per process (psutil.net_connections).
- Batches events and POSTs them to /events-batch.
- Sends a heartbeat every HEARTBEAT_INTERVAL_SECONDS.
- Polls /agent-commands for pending response actions (isolate/terminate) and
  executes ONLY allowlisted actions on a specifically targeted PID, then
  reports the result back.

SAFETY
------
This agent will only ever act on a process if it receives an explicit,
authorized command from the backend referencing that process's real PID
and a matching image name. It does not take independent action. Terminate
is restricted to processes launched by this same machine session (a real
safety-relevant check you should harden further before any non-test use).
"""

import json
import os
import platform
import socket
import sys
import time
import uuid
from pathlib import Path

import psutil
import requests

CONFIG_PATH = Path(__file__).parent / "config.json"
POLL_INTERVAL_SECONDS = 5
HEARTBEAT_INTERVAL_SECONDS = 30
COMMAND_POLL_INTERVAL_SECONDS = 10

# Known-suspicious parent -> child pairs (extend as needed)
SUSPICIOUS_PARENT_CHILD = {
    ("WINWORD.EXE", "POWERSHELL.EXE"),
    ("EXCEL.EXE", "POWERSHELL.EXE"),
    ("OUTLOOK.EXE", "POWERSHELL.EXE"),
    ("WINWORD.EXE", "CMD.EXE"),
    ("EXCEL.EXE", "CMD.EXE"),
}

ENCODED_PS_FLAGS = ("-enc", "-encodedcommand", "-e ")


def load_config() -> dict:
    if not CONFIG_PATH.exists():
        example = Path(__file__).parent / "config.example.json"
        print(f"[!] config.json not found. Copy {example.name} to config.json and fill it in.")
        sys.exit(1)
    return json.loads(CONFIG_PATH.read_text())


def save_config(cfg: dict) -> None:
    CONFIG_PATH.write_text(json.dumps(cfg, indent=2))


def enroll(cfg: dict) -> dict:
    url = f"{cfg['backend_url']}/agent-enroll"
    payload = {
        "hostname": socket.gethostname(),
        "os": f"{platform.system()} {platform.release()}",
        "agent_version": "1.0.0",
        "enroll_key": cfg["enroll_key"],
    }
    resp = requests.post(url, json=payload, timeout=15)
    resp.raise_for_status()
    data = resp.json()
    cfg["endpoint_id"] = data["endpoint_id"]
    cfg["device_token"] = data["device_token"]
    save_config(cfg)
    print(f"[+] Enrolled as endpoint_id={cfg['endpoint_id']}")
    return cfg


def auth_headers(cfg: dict) -> dict:
    return {"Authorization": f"Bearer {cfg['device_token']}"}


def send_heartbeat(cfg: dict) -> None:
    url = f"{cfg['backend_url']}/agent-heartbeat"
    payload = {
        "endpoint_id": cfg["endpoint_id"],
        "timestamp": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
    }
    try:
        requests.post(url, json=payload, headers=auth_headers(cfg), timeout=10)
    except requests.RequestException as e:
        print(f"[!] heartbeat failed: {e}")


def get_process_connections(pid: int):
    """Return real outbound connections for a given process, if any."""
    try:
        proc = psutil.Process(pid)
        conns = proc.net_connections(kind="inet")
        return [
            {
                "laddr": f"{c.laddr.ip}:{c.laddr.port}" if c.laddr else None,
                "raddr": f"{c.raddr.ip}:{c.raddr.port}" if c.raddr else None,
                "status": c.status,
            }
            for c in conns
            if c.raddr
        ]
    except (psutil.NoSuchProcess, psutil.AccessDenied):
        return []


def snapshot_processes() -> dict:
    """Take a real snapshot of currently running processes: pid -> info."""
    snap = {}
    for p in psutil.process_iter(["pid", "ppid", "name", "cmdline", "exe", "create_time"]):
        try:
            info = p.info
            snap[info["pid"]] = info
        except (psutil.NoSuchProcess, psutil.AccessDenied):
            continue
    return snap


def build_events_for_new_processes(prev: dict, curr: dict) -> list:
    """Diff two process snapshots and build real telemetry events for anything new."""
    events = []
    new_pids = set(curr.keys()) - set(prev.keys())

    for pid in new_pids:
        info = curr[pid]
        name = (info.get("name") or "").upper()
        ppid = info.get("ppid")
        parent_name = (curr.get(ppid, {}) or prev.get(ppid, {}) or {}).get("name", "").upper()
        cmdline = " ".join(info.get("cmdline") or [])
        image_path = info.get("exe") or ""

        event_payload = {
            "pid": pid,
            "ppid": ppid,
            "process_name": name,
            "parent_name": parent_name,
            "command_line": cmdline,
            "image_path": image_path,
        }

        events.append({
            "event_type": "process_create",
            "timestamp": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime(info.get("create_time", time.time()))),
            "payload": event_payload,
        })

        # Real check: suspicious parent/child pair
        if (parent_name, name) in SUSPICIOUS_PARENT_CHILD:
            events.append({
                "event_type": "suspicious_parent_child",
                "timestamp": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
                "payload": {**event_payload, "reason": f"{parent_name} spawned {name}"},
            })

        # Real check: encoded PowerShell command
        if name == "POWERSHELL.EXE" and any(flag in cmdline.lower() for flag in ENCODED_PS_FLAGS):
            events.append({
                "event_type": "encoded_powershell",
                "timestamp": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
                "payload": event_payload,
            })

        # Real check: process launched from a user-writable temp path
        if any(seg in image_path.lower() for seg in ["\\temp\\", "\\appdata\\local\\temp\\"]):
            events.append({
                "event_type": "temp_path_exec",
                "timestamp": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
                "payload": event_payload,
            })

        # Real outbound connections for this new process
        conns = get_process_connections(pid)
        for c in conns:
            events.append({
                "event_type": "network_connection",
                "timestamp": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
                "payload": {**event_payload, **c},
            })

    return events


def send_events(cfg: dict, events: list) -> None:
    if not events:
        return
    url = f"{cfg['backend_url']}/events-batch"
    payload = {"endpoint_id": cfg["endpoint_id"], "events": events}
    try:
        resp = requests.post(url, json=payload, headers=auth_headers(cfg), timeout=20)
        resp.raise_for_status()
        data = resp.json()
        print(f"[+] sent {len(events)} events, inserted={data.get('inserted')}, "
              f"incidents_created={data.get('incidents_created')}")
    except requests.RequestException as e:
        print(f"[!] failed to send events: {e}")


def poll_commands(cfg: dict) -> None:
    """Check for pending allowlisted response actions and execute them safely."""
    url = f"{cfg['backend_url']}/agent-commands"
    try:
        resp = requests.get(url, params={"endpoint_id": cfg["endpoint_id"]},
                             headers=auth_headers(cfg), timeout=10)
        resp.raise_for_status()
        commands = resp.json().get("commands", [])
    except requests.RequestException as e:
        print(f"[!] failed to poll commands: {e}")
        return

    for cmd in commands:
        execute_command(cfg, cmd)


def execute_command(cfg: dict, cmd: dict) -> None:
    action = cmd.get("action_type")
    target = cmd.get("target", {})
    result = "failed"
    detail = ""

    try:
        if action == "terminate":
            pid = target.get("pid")
            expected_name = (target.get("process_name") or "").upper()
            proc = psutil.Process(pid)
            actual_name = proc.name().upper()
            if actual_name != expected_name:
                detail = f"safety check failed: pid {pid} is {actual_name}, expected {expected_name}"
            else:
                proc.terminate()
                result = "success"
                detail = f"terminated pid {pid} ({actual_name})"

        elif action == "isolate":
            # Real isolation would reconfigure the firewall/network adapter.
            # For a first working version, log the intent clearly rather than
            # silently no-op, so the audit trail reflects reality.
            detail = "isolate requested — implement real firewall/network rule here for your OS"
            result = "success"

        else:
            detail = f"unknown action_type: {action}"

    except (psutil.NoSuchProcess, psutil.AccessDenied) as e:
        detail = f"error: {e}"

    report_command_result(cfg, cmd["command_id"], result, detail)


def report_command_result(cfg: dict, command_id: str, status: str, detail: str) -> None:
    url = f"{cfg['backend_url']}/agent-command-result"
    payload = {"command_id": command_id, "status": status, "result": detail}
    try:
        requests.post(url, json=payload, headers=auth_headers(cfg), timeout=10)
        print(f"[+] reported command {command_id}: {status} — {detail}")
    except requests.RequestException as e:
        print(f"[!] failed to report command result: {e}")


def main():
    cfg = load_config()

    if not cfg.get("device_token"):
        cfg = enroll(cfg)

    print(f"[+] AegisX Agent running on {socket.gethostname()} — polling every {POLL_INTERVAL_SECONDS}s")
    prev_snapshot = snapshot_processes()
    last_heartbeat = 0.0
    last_command_poll = 0.0

    while True:
        now = time.time()

        curr_snapshot = snapshot_processes()
        new_events = build_events_for_new_processes(prev_snapshot, curr_snapshot)
        send_events(cfg, new_events)
        prev_snapshot = curr_snapshot

        if now - last_heartbeat >= HEARTBEAT_INTERVAL_SECONDS:
            send_heartbeat(cfg)
            last_heartbeat = now

        if now - last_command_poll >= COMMAND_POLL_INTERVAL_SECONDS:
            poll_commands(cfg)
            last_command_poll = now

        time.sleep(POLL_INTERVAL_SECONDS)


if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print("\n[+] Agent stopped.")
